package dto;
// Generated 29/07/2018 06:44:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Arma generated by hbm2java
 */
public class Arma  implements java.io.Serializable {


     private int armaId;
     private Persona persona;
     private String tipoArma;
     private String marca;
     private String modelo;
     private String calibre;
     private String serial;
     private String paisFabricacion;
     private Integer capacidadCartucho;
     private String numeroFactura;
     private Date fechaFactura;
     private String tipoPorte;
     private String codigoDaexNumeroPorte;
     private String numeroSobre;
     private Date fechaVencimiento;
     private Boolean porteVigente;

    public Arma() {
    }

	
    public Arma(Persona persona) {
        this.persona = persona;
    }
    public Arma(Persona persona, String tipoArma, String marca, String modelo, String calibre, String serial, String paisFabricacion, Integer capacidadCartucho, String numeroFactura, Date fechaFactura, String tipoPorte, String codigoDaexNumeroPorte, String numeroSobre, Date fechaVencimiento, Boolean porteVigente) {
       this.persona = persona;
       this.tipoArma = tipoArma;
       this.marca = marca;
       this.modelo = modelo;
       this.calibre = calibre;
       this.serial = serial;
       this.paisFabricacion = paisFabricacion;
       this.capacidadCartucho = capacidadCartucho;
       this.numeroFactura = numeroFactura;
       this.fechaFactura = fechaFactura;
       this.tipoPorte = tipoPorte;
       this.codigoDaexNumeroPorte = codigoDaexNumeroPorte;
       this.numeroSobre = numeroSobre;
       this.fechaVencimiento = fechaVencimiento;
       this.porteVigente = porteVigente;
    }
   
    public int getArmaId() {
        return this.armaId;
    }
    
    public void setArmaId(int armaId) {
        this.armaId = armaId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTipoArma() {
        return this.tipoArma;
    }
    
    public void setTipoArma(String tipoArma) {
        this.tipoArma = tipoArma;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCalibre() {
        return this.calibre;
    }
    
    public void setCalibre(String calibre) {
        this.calibre = calibre;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getPaisFabricacion() {
        return this.paisFabricacion;
    }
    
    public void setPaisFabricacion(String paisFabricacion) {
        this.paisFabricacion = paisFabricacion;
    }
    public Integer getCapacidadCartucho() {
        return this.capacidadCartucho;
    }
    
    public void setCapacidadCartucho(Integer capacidadCartucho) {
        this.capacidadCartucho = capacidadCartucho;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public String getTipoPorte() {
        return this.tipoPorte;
    }
    
    public void setTipoPorte(String tipoPorte) {
        this.tipoPorte = tipoPorte;
    }
    public String getCodigoDaexNumeroPorte() {
        return this.codigoDaexNumeroPorte;
    }
    
    public void setCodigoDaexNumeroPorte(String codigoDaexNumeroPorte) {
        this.codigoDaexNumeroPorte = codigoDaexNumeroPorte;
    }
    public String getNumeroSobre() {
        return this.numeroSobre;
    }
    
    public void setNumeroSobre(String numeroSobre) {
        this.numeroSobre = numeroSobre;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Boolean getPorteVigente() {
        return this.porteVigente;
    }
    
    public void setPorteVigente(Boolean porteVigente) {
        this.porteVigente = porteVigente;
    }




}


