package dto;
// Generated 29/07/2018 06:44:32 AM by Hibernate Tools 4.3.1



/**
 * Constantes generated by hbm2java
 */
public class Constantes  implements java.io.Serializable {


     private int constantesId;
     private String key;
     private String value;
     private Boolean activo;

    public Constantes() {
    }

    public Constantes(String key, String value, Boolean activo) {
       this.key = key;
       this.value = value;
       this.activo = activo;
    }
   
    public int getConstantesId() {
        return this.constantesId;
    }
    
    public void setConstantesId(int constantesId) {
        this.constantesId = constantesId;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


