package dto;
// Generated 21/07/2018 03:28:31 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Renit generated by hbm2java
 */
public class Renit  implements java.io.Serializable {


     private int renitId;
     private Persona persona;
     private Boolean registrado;
     private String numeroCertificacion;
     private Date fechaVencimiento;
     private Boolean realizoCurso;
     private Set relModalidadRenits = new HashSet(0);

    public Renit() {
    }

	
    public Renit(Persona persona) {
        this.persona = persona;
    }
    public Renit(Persona persona, Boolean registrado, String numeroCertificacion, Date fechaVencimiento, Boolean realizoCurso) {
       this.persona = persona;
       this.registrado = registrado;
       this.numeroCertificacion = numeroCertificacion;
       this.fechaVencimiento = fechaVencimiento;
       this.realizoCurso = realizoCurso;
    }
   
    public int getRenitId() {
        return this.renitId;
    }
    
    public void setRenitId(int renitId) {
        this.renitId = renitId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Boolean getRegistrado() {
        return this.registrado;
    }
    
    public void setRegistrado(Boolean registrado) {
        this.registrado = registrado;
    }
    public String getNumeroCertificacion() {
        return this.numeroCertificacion;
    }
    
    public void setNumeroCertificacion(String numeroCertificacion) {
        this.numeroCertificacion = numeroCertificacion;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Boolean getRealizoCurso() {
        return this.realizoCurso;
    }
    
    public void setRealizoCurso(Boolean realizoCurso) {
        this.realizoCurso = realizoCurso;
    }
    public Set getRelModalidadRenits() {
        return this.relModalidadRenits;
    }
    
    public void setRelModalidadRenits(Set relModalidadRenits) {
        this.relModalidadRenits = relModalidadRenits;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Renit other = (Renit) obj;
        if (this.renitId != other.renitId) {
            return false;
        }
        return true;
    }




}


