package dto;
// Generated 29/07/2018 06:44:32 AM by Hibernate Tools 4.3.1



/**
 * Trabajo generated by hbm2java
 */
public class Trabajo  implements java.io.Serializable {


     private int trabajoId;
     private Persona persona;
     private String empresa;
     private String lugarEmpresa;
     private String parroquiaTrabajo;
     private String municipioTrabajo;
     private String estadoTrabajo;
     private String cargo;
     private String profesion;
     private String gradoInstruccion;

    public Trabajo() {
    }

	
    public Trabajo(Persona persona) {
        this.persona = persona;
    }
    public Trabajo(Persona persona, String empresa, String lugarEmpresa, String parroquiaTrabajo, String municipioTrabajo, String estadoTrabajo, String cargo, String profesion, String gradoInstruccion) {
       this.persona = persona;
       this.empresa = empresa;
       this.lugarEmpresa = lugarEmpresa;
       this.parroquiaTrabajo = parroquiaTrabajo;
       this.municipioTrabajo = municipioTrabajo;
       this.estadoTrabajo = estadoTrabajo;
       this.cargo = cargo;
       this.profesion = profesion;
       this.gradoInstruccion = gradoInstruccion;
    }
   
    public int getTrabajoId() {
        return this.trabajoId;
    }
    
    public void setTrabajoId(int trabajoId) {
        this.trabajoId = trabajoId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getLugarEmpresa() {
        return this.lugarEmpresa;
    }
    
    public void setLugarEmpresa(String lugarEmpresa) {
        this.lugarEmpresa = lugarEmpresa;
    }
    public String getParroquiaTrabajo() {
        return this.parroquiaTrabajo;
    }
    
    public void setParroquiaTrabajo(String parroquiaTrabajo) {
        this.parroquiaTrabajo = parroquiaTrabajo;
    }
    public String getMunicipioTrabajo() {
        return this.municipioTrabajo;
    }
    
    public void setMunicipioTrabajo(String municipioTrabajo) {
        this.municipioTrabajo = municipioTrabajo;
    }
    public String getEstadoTrabajo() {
        return this.estadoTrabajo;
    }
    
    public void setEstadoTrabajo(String estadoTrabajo) {
        this.estadoTrabajo = estadoTrabajo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public String getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(String gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }




}


