package dto;
// Generated 21/07/2018 03:28:31 AM by Hibernate Tools 4.3.1

import java.util.Date;


/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int usuarioId;
    private Persona persona;
    private String nombre;
    private String clave;
    private String tipoUsuario;
    private Boolean activo;
    private Boolean aceptado;
    private Date fechaCreado;

    public Date getFechaCreado() {
        return fechaCreado;
    }

    public void setFechaCreado(Date fechaCreado) {
        this.fechaCreado = fechaCreado;
    }

    public Boolean getAceptado() {
        return aceptado;
    }

    public void setAceptado(Boolean aceptado) {
        this.aceptado = aceptado;
    }

    public static final String USER_ADMIN = "Administrador";
    public static final String USER_NORMAL = "Normal";
    public static final String USER_SUPERVISOR = "Supervisor";

    public Usuario() {
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Usuario other = (Usuario) obj;
        if (this.usuarioId != other.usuarioId) {
            return false;
        }
        return true;
    }

    public Usuario(int usuarioId, Persona persona, String nombre, String clave, String tipoUsuario, Boolean activo) {
        this.usuarioId = usuarioId;
        this.persona = persona;
        this.nombre = nombre;
        this.clave = clave;
        this.tipoUsuario = tipoUsuario;
        this.activo = activo;
    }

    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public Usuario(Persona persona) {
        this.persona = persona;
    }

    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTipoUsuario() {
        return this.tipoUsuario;
    }

    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

}
